/* eslint-disable no-extend-native */
import reducer, { addCountry, initialState } from '../redux/countries/countries';

if (typeof String.prototype.replaceAll === 'undefined') {
  String.prototype.replaceAll = function replaceAll(match, replace) {
    return this.replace(new RegExp(match, 'g'), () => replace);
  };
}

test('add 3 countries', () => {
  let state = reducer(initialState, addCountry({
    id: 'us',
    name: 'US',
    today_confirmed: 333,
    today_new_deaths: 234,
    today_new_recovered: 123,
    today_recovered: 12345678,
    regions: {},
    flag: '',
    flagSVG: '',
    continent: 'North America',
  }));

  expect(state).toEqual({
    today_confirmed: 333,
    today_new_deaths: 234,
    today_new_recovered: 123,
    today_recovered: 12345678,
    countries: {
      us: {
        id: 'us',
        name: 'US',
        today_confirmed: 333,
        today_new_deaths: 234,
        today_new_recovered: 123,
        today_recovered: 12345678,
        regions: {},
        flag: '',
        flagSVG: '',
        continent: 'North America',
      },
    },
    europe: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
    africa: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
    asia: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
    north_america: {
      today_confirmed: 333,
      today_new_deaths: 234,
      today_new_recovered: 123,
      today_recovered: 12345678,
      countries: {
        us: {
          id: 'us',
          name: 'US',
          today_confirmed: 333,
          today_new_deaths: 234,
          today_new_recovered: 123,
          today_recovered: 12345678,
          regions: {},
          flag: '',
          flagSVG: '',
          continent: 'North America',
        },
      },
    },
    south_america: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
    oceania: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
  });

  state = reducer(state, addCountry({
    id: 'canada',
    name: 'Canada',
    today_confirmed: 234,
    today_new_deaths: 754,
    today_new_recovered: 432,
    today_recovered: 7464562,
    regions: {},
    flag: '',
    flagSVG: '',
    continent: 'North America',
  }));

  expect(state).toEqual({
    today_confirmed: 567,
    today_new_deaths: 988,
    today_new_recovered: 555,
    today_recovered: 19810240,
    countries: {
      us: {
        id: 'us',
        name: 'US',
        today_confirmed: 333,
        today_new_deaths: 234,
        today_new_recovered: 123,
        today_recovered: 12345678,
        regions: {},
        flag: '',
        flagSVG: '',
        continent: 'North America',
      },
      canada: {
        id: 'canada',
        name: 'Canada',
        today_confirmed: 234,
        today_new_deaths: 754,
        today_new_recovered: 432,
        today_recovered: 7464562,
        regions: {},
        flag: '',
        flagSVG: '',
        continent: 'North America',
      },
    },
    europe: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
    africa: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
    asia: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
    north_america: {
      today_confirmed: 567,
      today_new_deaths: 988,
      today_new_recovered: 555,
      today_recovered: 19810240,
      countries: {
        us: {
          id: 'us',
          name: 'US',
          today_confirmed: 333,
          today_new_deaths: 234,
          today_new_recovered: 123,
          today_recovered: 12345678,
          regions: {},
          flag: '',
          flagSVG: '',
          continent: 'North America',
        },
        canada: {
          id: 'canada',
          name: 'Canada',
          today_confirmed: 234,
          today_new_deaths: 754,
          today_new_recovered: 432,
          today_recovered: 7464562,
          regions: {},
          flag: '',
          flagSVG: '',
          continent: 'North America',
        },
      },
    },
    south_america: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
    oceania: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
  });

  state = reducer(state, addCountry({
    id: 'ukraine',
    name: 'Ukraine',
    today_confirmed: 839,
    today_new_deaths: 455,
    today_new_recovered: 3,
    today_recovered: 32455,
    regions: {},
    flag: '',
    flagSVG: '',
    continent: 'Europe',
  }));

  expect(state).toEqual({
    today_confirmed: 1406,
    today_new_deaths: 1443,
    today_new_recovered: 558,
    today_recovered: 19842695,
    countries: {
      us: {
        id: 'us',
        name: 'US',
        today_confirmed: 333,
        today_new_deaths: 234,
        today_new_recovered: 123,
        today_recovered: 12345678,
        regions: {},
        flag: '',
        flagSVG: '',
        continent: 'North America',
      },
      canada: {
        id: 'canada',
        name: 'Canada',
        today_confirmed: 234,
        today_new_deaths: 754,
        today_new_recovered: 432,
        today_recovered: 7464562,
        regions: {},
        flag: '',
        flagSVG: '',
        continent: 'North America',
      },
      ukraine: {
        id: 'ukraine',
        name: 'Ukraine',
        today_confirmed: 839,
        today_new_deaths: 455,
        today_new_recovered: 3,
        today_recovered: 32455,
        regions: {},
        flag: '',
        flagSVG: '',
        continent: 'Europe',
      },
    },
    europe: {
      today_confirmed: 839,
      today_new_deaths: 455,
      today_new_recovered: 3,
      today_recovered: 32455,
      countries: {
        ukraine: {
          id: 'ukraine',
          name: 'Ukraine',
          today_confirmed: 839,
          today_new_deaths: 455,
          today_new_recovered: 3,
          today_recovered: 32455,
          regions: {},
          flag: '',
          flagSVG: '',
          continent: 'Europe',
        },
      },
    },
    africa: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
    asia: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
    north_america: {
      today_confirmed: 567,
      today_new_deaths: 988,
      today_new_recovered: 555,
      today_recovered: 19810240,
      countries: {
        us: {
          id: 'us',
          name: 'US',
          today_confirmed: 333,
          today_new_deaths: 234,
          today_new_recovered: 123,
          today_recovered: 12345678,
          regions: {},
          flag: '',
          flagSVG: '',
          continent: 'North America',
        },
        canada: {
          id: 'canada',
          name: 'Canada',
          today_confirmed: 234,
          today_new_deaths: 754,
          today_new_recovered: 432,
          today_recovered: 7464562,
          regions: {},
          flag: '',
          flagSVG: '',
          continent: 'North America',
        },
      },
    },
    south_america: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
    oceania: {
      today_confirmed: 0,
      today_new_deaths: 0,
      today_new_recovered: 0,
      today_recovered: 0,
      countries: {},
    },
  });
});
